// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intrigue.proto

package intrigue

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewServiceRequest struct {
	Service              *NewService `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewServiceRequest) Reset()         { *m = NewServiceRequest{} }
func (m *NewServiceRequest) String() string { return proto.CompactTextString(m) }
func (*NewServiceRequest) ProtoMessage()    {}
func (*NewServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{0}
}

func (m *NewServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewServiceRequest.Unmarshal(m, b)
}
func (m *NewServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewServiceRequest.Marshal(b, m, deterministic)
}
func (m *NewServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewServiceRequest.Merge(m, src)
}
func (m *NewServiceRequest) XXX_Size() int {
	return xxx_messageInfo_NewServiceRequest.Size(m)
}
func (m *NewServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewServiceRequest proto.InternalMessageInfo

func (m *NewServiceRequest) GetService() *NewService {
	if m != nil {
		return m.Service
	}
	return nil
}

type Receipt struct {
	ServiceInfo          *ServiceSummary `protobuf:"bytes,1,opt,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Followup             string          `protobuf:"bytes,3,opt,name=Followup,proto3" json:"Followup,omitempty"`
	Error                string          `protobuf:"bytes,10,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{1}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetServiceInfo() *ServiceSummary {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *Receipt) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Receipt) GetFollowup() string {
	if m != nil {
		return m.Followup
	}
	return ""
}

func (m *Receipt) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DataRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{2}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *DataRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DataResponse struct {
	Responder            *Responder `protobuf:"bytes,2,opt,name=Responder,proto3" json:"Responder,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{3}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetResponder() *Responder {
	if m != nil {
		return m.Responder
	}
	return nil
}

func (m *DataResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{4}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type ServiceUpdate struct {
	Request              string   `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceUpdate) Reset()         { *m = ServiceUpdate{} }
func (m *ServiceUpdate) String() string { return proto.CompactTextString(m) }
func (*ServiceUpdate) ProtoMessage()    {}
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{5}
}

func (m *ServiceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceUpdate.Unmarshal(m, b)
}
func (m *ServiceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceUpdate.Marshal(b, m, deterministic)
}
func (m *ServiceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceUpdate.Merge(m, src)
}
func (m *ServiceUpdate) XXX_Size() int {
	return xxx_messageInfo_ServiceUpdate.Size(m)
}
func (m *ServiceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceUpdate proto.InternalMessageInfo

func (m *ServiceUpdate) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *ServiceUpdate) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ServiceUpdate) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Action struct {
	Request              string   `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	RemoteID             string   `protobuf:"bytes,5,opt,name=RemoteID,proto3" json:"RemoteID,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{6}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Action) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Action) GetRemoteID() string {
	if m != nil {
		return m.RemoteID
	}
	return ""
}

func (m *Action) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Action) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SummaryReceipt struct {
	Remotes              []*ProcessManager `protobuf:"bytes,1,rep,name=Remotes,proto3" json:"Remotes,omitempty"`
	Services             []*CoreService    `protobuf:"bytes,4,rep,name=Services,proto3" json:"Services,omitempty"`
	Error                string            `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SummaryReceipt) Reset()         { *m = SummaryReceipt{} }
func (m *SummaryReceipt) String() string { return proto.CompactTextString(m) }
func (*SummaryReceipt) ProtoMessage()    {}
func (*SummaryReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{7}
}

func (m *SummaryReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryReceipt.Unmarshal(m, b)
}
func (m *SummaryReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryReceipt.Marshal(b, m, deterministic)
}
func (m *SummaryReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryReceipt.Merge(m, src)
}
func (m *SummaryReceipt) XXX_Size() int {
	return xxx_messageInfo_SummaryReceipt.Size(m)
}
func (m *SummaryReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryReceipt proto.InternalMessageInfo

func (m *SummaryReceipt) GetRemotes() []*ProcessManager {
	if m != nil {
		return m.Remotes
	}
	return nil
}

func (m *SummaryReceipt) GetServices() []*CoreService {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *SummaryReceipt) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Ping struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{8}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Ping) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Ping) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Pong struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{9}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Pong) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Pong) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ProcessManager struct {
	ID                   string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string     `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	StartTime            string     `protobuf:"bytes,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	Errors               []string   `protobuf:"bytes,8,rep,name=Errors,proto3" json:"Errors,omitempty"`
	Status               string     `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Services             []*Service `protobuf:"bytes,4,rep,name=Services,proto3" json:"Services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProcessManager) Reset()         { *m = ProcessManager{} }
func (m *ProcessManager) String() string { return proto.CompactTextString(m) }
func (*ProcessManager) ProtoMessage()    {}
func (*ProcessManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{10}
}

func (m *ProcessManager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessManager.Unmarshal(m, b)
}
func (m *ProcessManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessManager.Marshal(b, m, deterministic)
}
func (m *ProcessManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessManager.Merge(m, src)
}
func (m *ProcessManager) XXX_Size() int {
	return xxx_messageInfo_ProcessManager.Size(m)
}
func (m *ProcessManager) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessManager.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessManager proto.InternalMessageInfo

func (m *ProcessManager) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProcessManager) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProcessManager) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ProcessManager) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *ProcessManager) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ProcessManager) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ProcessManager) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type NewService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Aliases              []string `protobuf:"bytes,2,rep,name=Aliases,proto3" json:"Aliases,omitempty"`
	IsServer             bool     `protobuf:"varint,3,opt,name=IsServer,proto3" json:"IsServer,omitempty"`
	IsClient             bool     `protobuf:"varint,4,opt,name=IsClient,proto3" json:"IsClient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewService) Reset()         { *m = NewService{} }
func (m *NewService) String() string { return proto.CompactTextString(m) }
func (*NewService) ProtoMessage()    {}
func (*NewService) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{11}
}

func (m *NewService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewService.Unmarshal(m, b)
}
func (m *NewService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewService.Marshal(b, m, deterministic)
}
func (m *NewService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewService.Merge(m, src)
}
func (m *NewService) XXX_Size() int {
	return xxx_messageInfo_NewService.Size(m)
}
func (m *NewService) XXX_DiscardUnknown() {
	xxx_messageInfo_NewService.DiscardUnknown(m)
}

var xxx_messageInfo_NewService proto.InternalMessageInfo

func (m *NewService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewService) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *NewService) GetIsServer() bool {
	if m != nil {
		return m.IsServer
	}
	return false
}

func (m *NewService) GetIsClient() bool {
	if m != nil {
		return m.IsClient
	}
	return false
}

type ServiceSummary struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Fingerprint          string   `protobuf:"bytes,3,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceSummary) Reset()         { *m = ServiceSummary{} }
func (m *ServiceSummary) String() string { return proto.CompactTextString(m) }
func (*ServiceSummary) ProtoMessage()    {}
func (*ServiceSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{12}
}

func (m *ServiceSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceSummary.Unmarshal(m, b)
}
func (m *ServiceSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceSummary.Marshal(b, m, deterministic)
}
func (m *ServiceSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceSummary.Merge(m, src)
}
func (m *ServiceSummary) XXX_Size() int {
	return xxx_messageInfo_ServiceSummary.Size(m)
}
func (m *ServiceSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceSummary proto.InternalMessageInfo

func (m *ServiceSummary) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServiceSummary) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ServiceSummary) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

type Service struct {
	Id                   string   `protobuf:"bytes,10,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,11,opt,name=Name,proto3" json:"Name,omitempty"`
	Registered           bool     `protobuf:"varint,22,opt,name=Registered,proto3" json:"Registered,omitempty"`
	Mode                 string   `protobuf:"bytes,23,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Address              string   `protobuf:"bytes,21,opt,name=Address,proto3" json:"Address,omitempty"`
	Path                 string   `protobuf:"bytes,12,opt,name=Path,proto3" json:"Path,omitempty"`
	LogPath              string   `protobuf:"bytes,20,opt,name=LogPath,proto3" json:"LogPath,omitempty"`
	Status               string   `protobuf:"bytes,14,opt,name=Status,proto3" json:"Status,omitempty"`
	Restarts             int32    `protobuf:"varint,15,opt,name=Restarts,proto3" json:"Restarts,omitempty"`
	Fails                int32    `protobuf:"varint,24,opt,name=Fails,proto3" json:"Fails,omitempty"`
	Pid                  int32    `protobuf:"varint,16,opt,name=Pid,proto3" json:"Pid,omitempty"`
	StartTime            string   `protobuf:"bytes,17,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	FailTime             string   `protobuf:"bytes,18,opt,name=FailTime,proto3" json:"FailTime,omitempty"`
	Errors               []string `protobuf:"bytes,19,rep,name=Errors,proto3" json:"Errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{13}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

func (m *Service) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *Service) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Service) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Service) GetLogPath() string {
	if m != nil {
		return m.LogPath
	}
	return ""
}

func (m *Service) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Service) GetRestarts() int32 {
	if m != nil {
		return m.Restarts
	}
	return 0
}

func (m *Service) GetFails() int32 {
	if m != nil {
		return m.Fails
	}
	return 0
}

func (m *Service) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Service) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Service) GetFailTime() string {
	if m != nil {
		return m.FailTime
	}
	return ""
}

func (m *Service) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CoreService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Mode                 string   `protobuf:"bytes,3,opt,name=Mode,proto3" json:"Mode,omitempty"`
	ParentID             string   `protobuf:"bytes,5,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Errors               []string `protobuf:"bytes,4,rep,name=Errors,proto3" json:"Errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoreService) Reset()         { *m = CoreService{} }
func (m *CoreService) String() string { return proto.CompactTextString(m) }
func (*CoreService) ProtoMessage()    {}
func (*CoreService) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{14}
}

func (m *CoreService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreService.Unmarshal(m, b)
}
func (m *CoreService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreService.Marshal(b, m, deterministic)
}
func (m *CoreService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreService.Merge(m, src)
}
func (m *CoreService) XXX_Size() int {
	return xxx_messageInfo_CoreService.Size(m)
}
func (m *CoreService) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreService.DiscardUnknown(m)
}

var xxx_messageInfo_CoreService proto.InternalMessageInfo

func (m *CoreService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CoreService) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CoreService) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *CoreService) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *CoreService) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

//
//Data Handlers
type Request struct {
	Sender               string   `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`
	Data1                string   `protobuf:"bytes,50,opt,name=Data1,proto3" json:"Data1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{15}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Request) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetData1() string {
	if m != nil {
		return m.Data1
	}
	return ""
}

type Responder struct {
	Result               string   `protobuf:"bytes,50,opt,name=Result,proto3" json:"Result,omitempty"`
	ErrorString          string   `protobuf:"bytes,98,opt,name=ErrorString,proto3" json:"ErrorString,omitempty"`
	HadError             bool     `protobuf:"varint,99,opt,name=HadError,proto3" json:"HadError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Responder) Reset()         { *m = Responder{} }
func (m *Responder) String() string { return proto.CompactTextString(m) }
func (*Responder) ProtoMessage()    {}
func (*Responder) Descriptor() ([]byte, []int) {
	return fileDescriptor_22f1d98c525e71fb, []int{16}
}

func (m *Responder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responder.Unmarshal(m, b)
}
func (m *Responder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responder.Marshal(b, m, deterministic)
}
func (m *Responder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responder.Merge(m, src)
}
func (m *Responder) XXX_Size() int {
	return xxx_messageInfo_Responder.Size(m)
}
func (m *Responder) XXX_DiscardUnknown() {
	xxx_messageInfo_Responder.DiscardUnknown(m)
}

var xxx_messageInfo_Responder proto.InternalMessageInfo

func (m *Responder) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Responder) GetErrorString() string {
	if m != nil {
		return m.ErrorString
	}
	return ""
}

func (m *Responder) GetHadError() bool {
	if m != nil {
		return m.HadError
	}
	return false
}

func init() {
	proto.RegisterType((*NewServiceRequest)(nil), "intrigue.NewServiceRequest")
	proto.RegisterType((*Receipt)(nil), "intrigue.Receipt")
	proto.RegisterType((*DataRequest)(nil), "intrigue.DataRequest")
	proto.RegisterType((*DataResponse)(nil), "intrigue.DataResponse")
	proto.RegisterType((*EmptyRequest)(nil), "intrigue.EmptyRequest")
	proto.RegisterType((*ServiceUpdate)(nil), "intrigue.ServiceUpdate")
	proto.RegisterType((*Action)(nil), "intrigue.Action")
	proto.RegisterType((*SummaryReceipt)(nil), "intrigue.SummaryReceipt")
	proto.RegisterType((*Ping)(nil), "intrigue.Ping")
	proto.RegisterType((*Pong)(nil), "intrigue.Pong")
	proto.RegisterType((*ProcessManager)(nil), "intrigue.ProcessManager")
	proto.RegisterType((*NewService)(nil), "intrigue.NewService")
	proto.RegisterType((*ServiceSummary)(nil), "intrigue.ServiceSummary")
	proto.RegisterType((*Service)(nil), "intrigue.Service")
	proto.RegisterType((*CoreService)(nil), "intrigue.CoreService")
	proto.RegisterType((*Request)(nil), "intrigue.Request")
	proto.RegisterType((*Responder)(nil), "intrigue.Responder")
}

func init() { proto.RegisterFile("intrigue.proto", fileDescriptor_22f1d98c525e71fb) }

var fileDescriptor_22f1d98c525e71fb = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0xee, 0x4c, 0x92, 0x26, 0x3d, 0x09, 0xd9, 0xd6, 0xdb, 0xed, 0x5a, 0x01, 0xa1, 0x68, 0xae,
	0x8a, 0x10, 0x95, 0x1a, 0x16, 0x21, 0xb8, 0x2b, 0xe9, 0x56, 0x1b, 0x41, 0xab, 0x68, 0xb2, 0x08,
	0x21, 0x71, 0xe3, 0x66, 0xbc, 0xb3, 0x96, 0x26, 0xe3, 0x60, 0x3b, 0xbb, 0xea, 0x35, 0x12, 0x77,
	0x5c, 0xc0, 0x7b, 0xf0, 0x24, 0x3c, 0x00, 0x6f, 0xc0, 0x73, 0x20, 0xff, 0x65, 0x3c, 0x4d, 0xb3,
	0xa2, 0xa2, 0x37, 0x7b, 0x37, 0x9f, 0x7d, 0xce, 0xf1, 0x77, 0x3e, 0x1f, 0x9f, 0x33, 0xd0, 0x67,
	0xa5, 0x12, 0x2c, 0x5f, 0xd1, 0x93, 0xa5, 0xe0, 0x8a, 0xa3, 0x8e, 0xc7, 0xc9, 0x18, 0x0e, 0xae,
	0xe8, 0xdb, 0x19, 0x15, 0x6f, 0xd8, 0x9c, 0xa6, 0xf4, 0xe7, 0x15, 0x95, 0x0a, 0x9d, 0x40, 0xdb,
	0xad, 0xe0, 0x68, 0x18, 0x1d, 0x77, 0x47, 0x87, 0x27, 0xeb, 0x00, 0x81, 0xb5, 0x37, 0x4a, 0x7e,
	0x8f, 0xa0, 0x9d, 0xd2, 0x39, 0x65, 0x4b, 0x85, 0xbe, 0x86, 0xae, 0xb4, 0xcb, 0x93, 0xf2, 0x15,
	0x77, 0xfe, 0xb8, 0xf2, 0x77, 0x3e, 0xb3, 0xd5, 0x62, 0x41, 0xc4, 0x4d, 0x1a, 0x1a, 0x23, 0x0c,
	0xed, 0x4b, 0x2a, 0x25, 0xc9, 0x29, 0x8e, 0x87, 0xd1, 0xf1, 0x5e, 0xea, 0x21, 0x1a, 0x40, 0xe7,
	0x82, 0x17, 0x05, 0x7f, 0xbb, 0x5a, 0xe2, 0x86, 0xd9, 0x5a, 0x63, 0x74, 0x08, 0xad, 0xe7, 0x42,
	0x70, 0x81, 0xc1, 0x6c, 0x58, 0x90, 0x4c, 0xa1, 0x7b, 0x4e, 0x14, 0xf1, 0x29, 0x7d, 0xaa, 0x19,
	0x9a, 0x4f, 0x47, 0xe9, 0xa0, 0xa2, 0xe4, 0x36, 0x52, 0x6f, 0x51, 0x45, 0x8c, 0xc3, 0x88, 0x3f,
	0x40, 0xcf, 0x46, 0x94, 0x4b, 0x5e, 0x4a, 0x8a, 0x4e, 0x61, 0xcf, 0x7e, 0x67, 0xd4, 0x5a, 0x76,
	0x47, 0x8f, 0xc3, 0xa0, 0x6e, 0x2b, 0xad, 0xac, 0xaa, 0xc0, 0x8d, 0x30, 0x70, 0x1f, 0x7a, 0xcf,
	0x17, 0x4b, 0x75, 0xe3, 0x8e, 0x4f, 0x7e, 0x84, 0x0f, 0x9c, 0x4a, 0xdf, 0x2f, 0x33, 0xa2, 0xa8,
	0xd6, 0x25, 0x24, 0xbf, 0x57, 0x31, 0xdd, 0xae, 0xd8, 0xdd, 0x47, 0xfd, 0x1a, 0xc1, 0xee, 0xd9,
	0x5c, 0x31, 0x5e, 0xbe, 0x23, 0xe8, 0x11, 0xec, 0xbe, 0x24, 0x22, 0xa7, 0xca, 0xc5, 0x74, 0x48,
	0x5f, 0x42, 0x4a, 0x17, 0x5c, 0xd1, 0xc9, 0x39, 0x6e, 0xd9, 0x4b, 0xf0, 0x38, 0x24, 0xd2, 0xfc,
	0x2f, 0x44, 0x7e, 0x8b, 0xa0, 0xef, 0x6b, 0xc0, 0x55, 0xce, 0x48, 0x13, 0xd2, 0xe1, 0x24, 0x8e,
	0x86, 0x8d, 0x7a, 0xd5, 0x4c, 0x05, 0x9f, 0x53, 0x29, 0x2f, 0x49, 0x49, 0x72, 0x2a, 0x52, 0x6f,
	0x88, 0x4e, 0xa1, 0xe3, 0xa4, 0x92, 0xb8, 0x69, 0x9c, 0x9e, 0x54, 0x4e, 0x63, 0x2e, 0xa8, 0xaf,
	0xd5, 0xb5, 0xd9, 0x16, 0x3e, 0x2f, 0xa0, 0x39, 0x65, 0x65, 0xae, 0x73, 0x9f, 0x29, 0xa2, 0x56,
	0xd2, 0x89, 0xe2, 0x10, 0x42, 0xd0, 0x7c, 0xc9, 0x16, 0x5e, 0x65, 0xf3, 0xfd, 0x8e, 0x48, 0xfc,
	0x41, 0x22, 0xfd, 0x15, 0x41, 0xbf, 0x9e, 0x38, 0xea, 0x43, 0x3c, 0x39, 0x77, 0x01, 0xe3, 0xc9,
	0xb9, 0x0e, 0x76, 0x45, 0xaa, 0x60, 0xfa, 0x5b, 0x5f, 0xc5, 0x59, 0x96, 0x09, 0x2a, 0xa5, 0x0b,
	0xe7, 0x21, 0xfa, 0x08, 0xf6, 0x66, 0x8a, 0x08, 0x65, 0xce, 0xb7, 0x37, 0x58, 0x2d, 0x68, 0xc2,
	0xe6, 0x5c, 0x89, 0x3b, 0xc3, 0x86, 0x26, 0x6c, 0x51, 0x90, 0x48, 0xbb, 0x96, 0xc8, 0x67, 0x1b,
	0xda, 0x1f, 0x6c, 0x3c, 0xf3, 0x4a, 0xf7, 0x44, 0x00, 0x54, 0xbd, 0x63, 0x4d, 0x3c, 0xba, 0x45,
	0xbc, 0x60, 0x44, 0x52, 0x89, 0x63, 0xc3, 0xc0, 0x43, 0x5d, 0x79, 0x13, 0xa9, 0x5d, 0xa9, 0x95,
	0xa8, 0x93, 0xae, 0xb1, 0xdd, 0x1b, 0x17, 0x8c, 0x96, 0xca, 0x94, 0x9e, 0xd9, 0xb3, 0x38, 0xf9,
	0x09, 0xfa, 0xf5, 0x7e, 0x13, 0x8a, 0x13, 0xd5, 0xc5, 0xb1, 0xd2, 0xc6, 0x6b, 0x69, 0x87, 0xd0,
	0xbd, 0x60, 0x65, 0x4e, 0xc5, 0x52, 0xb0, 0x52, 0x39, 0x29, 0xc3, 0xa5, 0xe4, 0xef, 0x78, 0xdd,
	0x27, 0x8d, 0x77, 0xe6, 0x3a, 0x50, 0x3c, 0xc9, 0xd6, 0xf9, 0x75, 0x83, 0xfc, 0x3e, 0x06, 0x48,
	0x69, 0xce, 0xa4, 0xa2, 0x82, 0x66, 0xf8, 0xc8, 0x70, 0x0d, 0x56, 0xb4, 0xcf, 0x25, 0xcf, 0x28,
	0x7e, 0x6a, 0x7d, 0xf4, 0x77, 0xc8, 0xf7, 0x49, 0x9d, 0x2f, 0x82, 0xe6, 0x94, 0xa8, 0xd7, 0xb8,
	0x67, 0xad, 0xf5, 0xb7, 0xb6, 0xfe, 0x8e, 0xe7, 0x66, 0xf9, 0xd0, 0x5a, 0x3b, 0x18, 0x5c, 0x62,
	0xbf, 0x76, 0x89, 0xe6, 0x4d, 0x4b, 0x5d, 0x03, 0x12, 0x3f, 0x1a, 0x46, 0xc7, 0xad, 0x74, 0x8d,
	0x75, 0x55, 0x5e, 0x10, 0x56, 0x48, 0x8c, 0xcd, 0x86, 0x05, 0x68, 0x1f, 0x1a, 0x53, 0x96, 0xe1,
	0x7d, 0xb3, 0xa6, 0x3f, 0xeb, 0x65, 0x75, 0x70, 0xbb, 0xac, 0x74, 0xeb, 0x26, 0xac, 0x30, 0x9b,
	0xc8, 0xb5, 0x6e, 0x87, 0x83, 0x92, 0x7b, 0x1c, 0x96, 0x5c, 0xf2, 0x4b, 0x04, 0xdd, 0xe0, 0xf5,
	0x6e, 0xad, 0x16, 0xa7, 0x4c, 0xbc, 0xa1, 0x8c, 0xd1, 0xb1, 0x11, 0xe8, 0x38, 0x80, 0xce, 0x94,
	0x08, 0x5a, 0xaa, 0xaa, 0x77, 0x79, 0x1c, 0xb0, 0x68, 0xd6, 0x58, 0xe4, 0x10, 0xb6, 0xc4, 0x19,
	0x35, 0x8d, 0xde, 0x3f, 0x66, 0x83, 0xb6, 0xb6, 0xca, 0x23, 0xd8, 0xbd, 0xa4, 0xea, 0x35, 0xcf,
	0x1c, 0x09, 0x87, 0xb4, 0xa4, 0x7a, 0x86, 0x9c, 0xe2, 0x91, 0x7d, 0xe8, 0x06, 0x24, 0x24, 0x98,
	0x24, 0xda, 0x35, 0xa5, 0x72, 0x55, 0x28, 0x67, 0xe3, 0x90, 0xae, 0x47, 0xc3, 0x6b, 0xa6, 0x04,
	0x2b, 0x73, 0x7c, 0x6d, 0xeb, 0x31, 0x58, 0xd2, 0x39, 0xbe, 0x20, 0x99, 0x6d, 0x24, 0x73, 0xfb,
	0x12, 0x3c, 0x1e, 0xfd, 0x19, 0x43, 0x6b, 0x4c, 0xae, 0x49, 0x81, 0xc6, 0xf0, 0xc8, 0xd7, 0x9c,
	0x97, 0xf7, 0xc3, 0x3b, 0xc7, 0xbb, 0x4d, 0x7d, 0x50, 0x1b, 0x94, 0xa6, 0x53, 0x27, 0x3b, 0xe8,
	0x1b, 0x40, 0x76, 0x36, 0xd9, 0x50, 0x82, 0x98, 0x91, 0xf2, 0x74, 0xe3, 0xfd, 0x5b, 0xa3, 0xbb,
	0x63, 0x7c, 0x09, 0x4d, 0x9d, 0x3e, 0x0a, 0x3a, 0x76, 0x30, 0xb1, 0x07, 0x47, 0xb7, 0x97, 0xed,
	0xd8, 0x35, 0x8e, 0x6d, 0xff, 0x9c, 0xf7, 0x2b, 0x23, 0x3b, 0xd6, 0x06, 0xe1, 0xaf, 0x46, 0x6d,
	0xbe, 0x24, 0x3b, 0xe8, 0x13, 0x68, 0x9d, 0x15, 0xec, 0x0d, 0x45, 0xfd, 0x60, 0xb2, 0xb0, 0x32,
	0x1f, 0x84, 0x98, 0x97, 0x79, 0xb2, 0x33, 0xfa, 0x27, 0xd2, 0xd7, 0xa0, 0x87, 0x0c, 0x7a, 0x06,
	0xbd, 0x2b, 0xae, 0xd8, 0xab, 0x1b, 0x37, 0x38, 0x37, 0xcf, 0xdc, 0x58, 0xf9, 0x3f, 0x24, 0x1f,
	0x42, 0xda, 0x7b, 0x24, 0xfa, 0x47, 0x03, 0xda, 0x63, 0x5e, 0x2a, 0xc1, 0x0b, 0xf4, 0x05, 0xf4,
	0xcc, 0xbb, 0xf5, 0x75, 0xb1, 0x49, 0x7c, 0xcb, 0x45, 0xf6, 0x5d, 0xcf, 0xb8, 0xa7, 0xe3, 0x33,
	0xe8, 0x7e, 0xcb, 0x8a, 0xe2, 0xde, 0xc7, 0xbd, 0x17, 0xca, 0xa2, 0xaf, 0x00, 0x66, 0x8a, 0x2f,
	0xdd, 0x98, 0x0a, 0xca, 0x39, 0xfc, 0xd9, 0xbb, 0xf3, 0x94, 0xeb, 0x5d, 0xf3, 0x9b, 0xfe, 0xf9,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xa5, 0x54, 0x29, 0xb8, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CabalClient is the client API for Cabal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CabalClient interface {
	RegisterService(ctx context.Context, in *NewServiceRequest, opts ...grpc.CallOption) (*Receipt, error)
	UpdateRegistration(ctx context.Context, in *ServiceUpdate, opts ...grpc.CallOption) (*Receipt, error)
	Data(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Summary(ctx context.Context, in *Action, opts ...grpc.CallOption) (*SummaryReceipt, error)
	Alive(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type cabalClient struct {
	cc *grpc.ClientConn
}

func NewCabalClient(cc *grpc.ClientConn) CabalClient {
	return &cabalClient{cc}
}

func (c *cabalClient) RegisterService(ctx context.Context, in *NewServiceRequest, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Cabal/RegisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cabalClient) UpdateRegistration(ctx context.Context, in *ServiceUpdate, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Cabal/UpdateRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cabalClient) Data(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/intrigue.Cabal/Data", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cabalClient) Summary(ctx context.Context, in *Action, opts ...grpc.CallOption) (*SummaryReceipt, error) {
	out := new(SummaryReceipt)
	err := c.cc.Invoke(ctx, "/intrigue.Cabal/Summary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cabalClient) Alive(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/intrigue.Cabal/Alive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CabalServer is the server API for Cabal service.
type CabalServer interface {
	RegisterService(context.Context, *NewServiceRequest) (*Receipt, error)
	UpdateRegistration(context.Context, *ServiceUpdate) (*Receipt, error)
	Data(context.Context, *DataRequest) (*DataResponse, error)
	Summary(context.Context, *Action) (*SummaryReceipt, error)
	Alive(context.Context, *Ping) (*Pong, error)
}

func RegisterCabalServer(s *grpc.Server, srv CabalServer) {
	s.RegisterService(&_Cabal_serviceDesc, srv)
}

func _Cabal_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabalServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Cabal/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabalServer).RegisterService(ctx, req.(*NewServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cabal_UpdateRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabalServer).UpdateRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Cabal/UpdateRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabalServer).UpdateRegistration(ctx, req.(*ServiceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cabal_Data_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabalServer).Data(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Cabal/Data",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabalServer).Data(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cabal_Summary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabalServer).Summary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Cabal/Summary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabalServer).Summary(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cabal_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CabalServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Cabal/Alive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CabalServer).Alive(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cabal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intrigue.Cabal",
	HandlerType: (*CabalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _Cabal_RegisterService_Handler,
		},
		{
			MethodName: "UpdateRegistration",
			Handler:    _Cabal_UpdateRegistration_Handler,
		},
		{
			MethodName: "Data",
			Handler:    _Cabal_Data_Handler,
		},
		{
			MethodName: "Summary",
			Handler:    _Cabal_Summary_Handler,
		},
		{
			MethodName: "Alive",
			Handler:    _Cabal_Alive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intrigue.proto",
}

// RemoteClient is the client API for Remote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteClient interface {
	NotifyAction(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Action, error)
	Summary(ctx context.Context, in *Action, opts ...grpc.CallOption) (*SummaryReceipt, error)
	UpdateRegistration(ctx context.Context, in *ServiceUpdate, opts ...grpc.CallOption) (*Receipt, error)
	Alive(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type remoteClient struct {
	cc *grpc.ClientConn
}

func NewRemoteClient(cc *grpc.ClientConn) RemoteClient {
	return &remoteClient{cc}
}

func (c *remoteClient) NotifyAction(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Action, error) {
	out := new(Action)
	err := c.cc.Invoke(ctx, "/intrigue.Remote/NotifyAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) Summary(ctx context.Context, in *Action, opts ...grpc.CallOption) (*SummaryReceipt, error) {
	out := new(SummaryReceipt)
	err := c.cc.Invoke(ctx, "/intrigue.Remote/Summary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) UpdateRegistration(ctx context.Context, in *ServiceUpdate, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Remote/UpdateRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteClient) Alive(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/intrigue.Remote/Alive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteServer is the server API for Remote service.
type RemoteServer interface {
	NotifyAction(context.Context, *Action) (*Action, error)
	Summary(context.Context, *Action) (*SummaryReceipt, error)
	UpdateRegistration(context.Context, *ServiceUpdate) (*Receipt, error)
	Alive(context.Context, *Ping) (*Pong, error)
}

func RegisterRemoteServer(s *grpc.Server, srv RemoteServer) {
	s.RegisterService(&_Remote_serviceDesc, srv)
}

func _Remote_NotifyAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).NotifyAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Remote/NotifyAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).NotifyAction(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_Summary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).Summary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Remote/Summary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).Summary(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_UpdateRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).UpdateRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Remote/UpdateRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).UpdateRegistration(ctx, req.(*ServiceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remote_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Remote/Alive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServer).Alive(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _Remote_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intrigue.Remote",
	HandlerType: (*RemoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyAction",
			Handler:    _Remote_NotifyAction_Handler,
		},
		{
			MethodName: "Summary",
			Handler:    _Remote_Summary_Handler,
		},
		{
			MethodName: "UpdateRegistration",
			Handler:    _Remote_UpdateRegistration_Handler,
		},
		{
			MethodName: "Alive",
			Handler:    _Remote_Alive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intrigue.proto",
}

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	StartService(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Receipt, error)
	RestartService(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Receipt, error)
	KillService(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Receipt, error)
	Summary(ctx context.Context, in *Action, opts ...grpc.CallOption) (*SummaryReceipt, error)
	UpdateRegistration(ctx context.Context, in *ServiceUpdate, opts ...grpc.CallOption) (*Receipt, error)
	Alive(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	StopServer(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Receipt, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) StartService(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Control/StartService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) RestartService(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Control/RestartService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) KillService(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Control/KillService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Summary(ctx context.Context, in *Action, opts ...grpc.CallOption) (*SummaryReceipt, error) {
	out := new(SummaryReceipt)
	err := c.cc.Invoke(ctx, "/intrigue.Control/Summary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) UpdateRegistration(ctx context.Context, in *ServiceUpdate, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Control/UpdateRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Alive(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/intrigue.Control/Alive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) StopServer(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Receipt, error) {
	out := new(Receipt)
	err := c.cc.Invoke(ctx, "/intrigue.Control/StopServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	StartService(context.Context, *Action) (*Receipt, error)
	RestartService(context.Context, *Action) (*Receipt, error)
	KillService(context.Context, *Action) (*Receipt, error)
	Summary(context.Context, *Action) (*SummaryReceipt, error)
	UpdateRegistration(context.Context, *ServiceUpdate) (*Receipt, error)
	Alive(context.Context, *Ping) (*Pong, error)
	StopServer(context.Context, *EmptyRequest) (*Receipt, error)
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/StartService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).StartService(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/RestartService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).RestartService(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_KillService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).KillService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/KillService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).KillService(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Summary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Summary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/Summary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Summary(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_UpdateRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).UpdateRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/UpdateRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).UpdateRegistration(ctx, req.(*ServiceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/Alive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Alive(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intrigue.Control/StopServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).StopServer(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "intrigue.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartService",
			Handler:    _Control_StartService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _Control_RestartService_Handler,
		},
		{
			MethodName: "KillService",
			Handler:    _Control_KillService_Handler,
		},
		{
			MethodName: "Summary",
			Handler:    _Control_Summary_Handler,
		},
		{
			MethodName: "UpdateRegistration",
			Handler:    _Control_UpdateRegistration_Handler,
		},
		{
			MethodName: "Alive",
			Handler:    _Control_Alive_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _Control_StopServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intrigue.proto",
}
